### ISSUE TITLE
ERROR 

### ISSUE THREAD

**Issue by tolgatasci** [KamvaHQ/moloquent#3]
```
<?php

namespace App;

use Kamva\Moloquent\Moloquent;

class Artist extends Moloquent
{

    protected $connection = 'mongodb';
    protected $collection = 'tt_artists';

    protected $fillable = [
        'name','image'
    ];


    public function musics(){
        return $this->IncludedIn('App\Music');
    }
}

```

DUMP

```
Declaration of Kamva\Moloquent\Traits\HybridRelations::belongsToMany($related, $collection = NULL, $foreignKey = NULL, $otherKey = NULL, $relation = NULL) should be compatible with Jenssegers\Mongodb\Eloquent\Model::belongsToMany($related, $collection = NULL, $foreignKey = NULL, $otherKey = NULL, $parentKey = NULL, $relatedKey = NULL, $relation = NULL)
  
```

**Comment by behzadsh** [comment]
Hi,
Could you tell what version of laravel you're using?

**Comment by tolgatasci** [comment]
latest 5.7 

An extended jenssegers/laravel-mongodb library 

previously installed

**Comment by tolgatasci** [comment]
I saw now. I'm sorry, you specifically mentioned. 5.2 I will wait patiently for this version upgrade.

**Comment by behzadsh** [comment]
@tolgatasci I'm a little busy right now, and It may take a while to update this package for laravel 5.7. feel free to do a pull request.

**Comment by iqbalme** [comment]
Hello, i'm using laravel 5.8 and still face this problem. is there any fix?

**Comment by behzadsh** [comment]
@iqbalme Hi
No, as I mentioned before, I'm busy right now and It's a while I do not programming in php, so still there is no fix for this issue.

Maybe next week If I find free time I work on it. Pull requests are always welcome.

**Comment by iqbalme** [comment]
i hope you will have a free time to fix it soon, i need it in my project. Thank you.
